In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

reverse = arr[::-1]

print(reverse)


[5 4 3 2 1]


In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])

flattened = array1.flatten()

print(flattened)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(np.array_equal(arr1, arr2))

True


In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)

max_count = np.max(counts)
most_frequent = values[counts == max_count][0]

indices = np.where(x == most_frequent)[0]

print(most_frequent)
print(indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

max_count = np.max(counts)
most_frequent = values[counts == max_count][0]

indices = np.where(y == most_frequent)[0]

print(most_frequent)
print(indices)

1
[0 5 7 8 9]
1
[0 1 2]


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
print(np.sum(gfg, axis=1))
print(np.sum(gfg, axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [ ]:
n_array = np.array([
    [55, 25, 15],
    [30, 44, 2],
    [11, 45, 77]
])
print(np.trace(n_array))

176


In [ ]:
eigenvalues = np.linalg.eigvals(n_array)

print(eigenvalues)

[98.16835147 28.097044   49.73460452]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(n_array)

print(eigenvectors)

[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
inverse = np.linalg.inv(n_array)

print(inverse)

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
determinant = np.linalg.det(n_array)

print(determinant)

137180.0000000001


In [ ]:
p = np.array([
    [1, 2],
    [2, 3]
])

q = np.array([
    [4, 5],
    [6, 7]
])
print(np.matmul(p, q))
print(np.cov(p, q))

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p = np.array([
    [1, 2],
    [2, 3],
    [4, 5]
])

q = np.array([
    [4, 5, 1],
    [6, 7, 2]
])
print(np.matmul(p, q))


[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
x = np.array([
    [2, 3, 4],
    [3, 2, 9]
])

y = np.array([
    [1, 5, 0],
    [5, 10, 3]
])
print(np.inner(x, y))
print(np.outer(x, y))
cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
import numpy as np

# Q2 (a)
array = np.array([
    [1, -2, 3],
    [-4, 5, -6]
])

# i. Element-wise absolute value
print("Absolute value:")
print(np.abs(array))

# ii. 25th, 50th and 75th percentile

print("\nPercentile of flattened array:")
print(np.percentile(array, [25, 50, 75]))

print("\nPercentile for each column:")
print(np.percentile(array, [25, 50, 75], axis=0))

print("\nPercentile for each row:")
print(np.percentile(array, [25, 50, 75], axis=1))

# iii. Mean, Median and Standard Deviation

print("\nMean of flattened array:")
print(np.mean(array))

print("Median of flattened array:")
print(np.median(array))

print("Standard deviation of flattened array:")
print(np.std(array))

print("\nMean of each column:")
print(np.mean(array, axis=0))

print("Median of each column:")
print(np.median(array, axis=0))

print("Standard deviation of each column:")
print(np.std(array, axis=0))

print("\nMean of each row:")
print(np.mean(array, axis=1))

print("Median of each row:")
print(np.median(array, axis=1))

print("Standard deviation of each row:")
print(np.std(array, axis=1))


# Q2 (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("\nFloor:")
print(np.floor(a))

print("\nCeiling:")
print(np.ceil(a))

print("\nTruncated:")
print(np.trunc(a))

print("\nRounded:")
print(np.round(a))

Absolute value:
[[1 2 3]
 [4 5 6]]

Percentile of flattened array:
[-3.5 -0.5  2.5]

Percentile for each column:
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Percentile for each row:
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Mean of flattened array:
-0.5
Median of flattened array:
-0.5
Standard deviation of flattened array:
3.8622100754188224

Mean of each column:
[-1.5  1.5 -1.5]
Median of each column:
[-1.5  1.5 -1.5]
Standard deviation of each column:
[2.5 3.5 4.5]

Mean of each row:
[ 0.66666667 -1.66666667]
Median of each row:
[ 1. -4.]
Standard deviation of each row:
[2.05480467 4.78423336]

Floor:
[-2. -2. -1.  0.  1.  1.  3.]

Ceiling:
[-1. -1. -0.  1.  2.  2.  3.]

Truncated:
[-1. -1. -0.  0.  1.  1.  3.]

Rounded:
[-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
import numpy as np

# Q3 (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
print("Sorted array:")
print(np.sort(array))

# ii. Indices of sorted array
print("\nIndices of sorted array:")
print(np.argsort(array))

# iii. 4 smallest elements
print("\n4 smallest elements:")
print(np.sort(array)[:4])

# iv. 5 largest elements
print("\n5 largest elements:")
print(np.sort(array)[-5:])


# Q3 (b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
print("\nInteger elements:")
print(array[array % 1 == 0])

# ii. Float elements only
print("\nFloat elements:")
print(array[array % 1 != 0])

Sorted array:
[ 10  16  16  52  54  62 453]

Indices of sorted array:
[0 3 4 1 5 2 6]

4 smallest elements:
[10 16 16 52]

5 largest elements:
[ 16  52  54  62 453]

Integer elements:
[1. 2. 3. 2.]

Float elements:
[1.2 2.2]


In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)

    # Grayscale image
    if len(arr.shape) == 2:
        np.savetxt("image.txt", arr, fmt="%d")
        print("Grayscale image saved as image.txt")

    # RGB image
    elif len(arr.shape) == 3:
        # Convert 3D RGB array into 2D before saving
        arr_2d = arr.reshape(-1, arr.shape[2])
        np.savetxt("image.txt", arr_2d, fmt="%d")
        print("RGB image saved as image.txt")

    return arr
    img_to_array("image.png")

In [6]:
from PIL import Image
import numpy as np

In [10]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)

    # RGB or RGBA image
    if img.mode == "RGB" or img.mode == "RGBA":
        img = img.convert("RGB")
        arr = np.array(img)
        np.savetxt("rgb_image.txt", arr.reshape(-1, 3), fmt="%d")
        print("RGB image saved successfully")

    # Grayscale image
    elif img.mode == "L":
        arr = np.array(img)
        np.savetxt("grayscale_image.txt", arr, fmt="%d")
        print("Grayscale image saved successfully")

    else:
        print("Unsupported image type")

In [11]:
img_to_array("image.png")

RGB image saved successfully
